# Generated by Django 5.1.2 on 2024-10-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evapp', '0017_apt_aptcharger_charger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('모델명', models.CharField(max_length=255)),
                ('번호', models.CharField(max_length=20)),
                ('판매량', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'danawa',
            },
        ),
    ]
